# Generated by Django 2.1.2 on 2018-10-26 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorebot_game', '0001_initial'),
        ('scorebot_grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='captured',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker_flags', to='scorebot_game.GameTeam'),
        ),
        migrations.AddField(
            model_name='flag',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='scorebot_game.GameTeam'),
        ),
        migrations.AddField(
            model_name='host',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='scorebot_game.GameTeam'),
        ),
    ]
