# Generated by Django 2.2.1 on 2019-06-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorebot_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='Tolerance',
            field=models.PositiveSmallIntegerField(blank=True, db_column='tolerance', null=True, verbose_name='Content Match Tolerance'),
        ),
    ]
